### ISSUE TITLE
Serialize sdk network calls to prevent races

### ISSUE THREAD

**Issue by ratelle** [Optable/optable-web-sdk#28]
Multiple calls to sdk methods are currently racy. For example, a call to identify followed by a call to targeting can have the targeting call reach the sandbox first. Both calls can also be executed concurrently in the sandbox causing multiple passport to be created with the last call 'winning'.

We need to serialize calls to the sandbox to enforce an orderding. This should probably be implemented in the command queue by having it await on a call before running the next one.

**Comment by zapo** [comment]
@ratelle It can already be prevented by using the returned promises:

in async function context (note I believe some browser now support await in top level context as well)
```
async function do() {
  await sdk.identify()
  await sdk.targeting()
  console.log("done")
}
```

Or in non async function context 

```
  sdk.identify()
  .then(() => sdk.targeting())
  .then(() => console.log("done"))
```

This however doesn't prevent against server side target after identify race, but I don't think this ticket is about that.
